### ISSUE TITLE
"ModuleNotFoundError: No module named 'core.pe._block'" on Fedora 37

### ISSUE THREAD

**Issue by UtopianElectronics** [arsenetar/dupeguru#1074]
**Describe the bug**
This issue happened after upgrading from Fedora 36 to Fedora 37.

**To Reproduce**
Just run to program, and this message would be displayed in the terminal:

```
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 88, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/dupeguru", line 71, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 26, in <module>
    from core import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from core.pe import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from core.pe._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'core.pe._block'
Fontconfig error: "/home/utopianelectronics/.config/fontconfig/conf.d", line 1: Extra content at the end of the document

```

**Additional context**
My installed Python version is 3.11.0 (this is what I get by running `$ python -V`).

The common fix I found, for example [here](https://github.com/arsenetar/dupeguru/issues/519#issuecomment-1328947293), doesn't solve the issue:

```
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-310-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-310-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-310-x86_64-linux-gnu.so
```

results in:

```
ln: failed to create hard link '/usr/share/dupeguru/core/pe/_cache.cpython-310-x86_64-linux-gnu.so': File exists
ln: failed to create hard link '/usr/share/dupeguru/core/pe/_block.cpython-310-x86_64-linux-gnu.so': File exists
ln: failed to create hard link '/usr/share/dupeguru/qt/pe/_block_qt.cpython-310-x86_64-linux-gnu.so': File exists
```

**Comment by arsenetar** [comment]
The shared libraries are python version specific, so the common fix you have listed is for python 3.10 by renaming the python 3.9 shared libraries (which do not have an incompatibilities in that case).  The current release deb and rpm files only provide python 3.7-3.10 shared libraries and the release pages state the supported versions.  The error you get when trying to `ln` is due to the file for 3.10 already being provided.  Its possible that if you symlink the 3.10 file to a 3.11 named version that will work.

Building and running from source does work on Fedora 37, the package names listed in the readme at https://github.com/arsenetar/dupeguru#system-setup are a bit different since those are the Debian names for the packages.

**Comment by UtopianElectronics** [comment]
> Its possible that if you symlink the 3.10 file to a 3.11 named version that will work.

It works now, thank you.

However, the (View -> Details) pane doesn't show any previews for image files. Is this a bug?

**Comment by glubsy** [comment]
> > Its possible that if you symlink the 3.10 file to a 3.11 named version that will work.
> 
> It works now, thank you.
> 
> However, the (View -> Details) pane doesn't show any previews for image files. Is this a bug?

Make sure you are using the "Picture" Application Mode.

**Comment by UtopianElectronics** [comment]
> Make sure you are using the "Picture" Application Mode.

Solved.

**Comment by tsilvs** [comment]
Having the same issue on Fedora Silverblue 39.

Proposed shared object link solution can't be implemented straightforwardly due to OStree immutability.

Python version:
```
$ python -V
Python 3.12.1
```

Error when linking (with elevated privileges):
```
# ln /usr/share/dupeguru/core/pe/_cache.cpython-39-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-312-x86_64-linux-gnu.so
ln: failed to create hard link '/usr/share/dupeguru/core/pe/_cache.cpython-312-x86_64-linux-gnu.so': Read-only file system
```

In case of `rpm-ostree` package management could it possibly be solved by creating an `.rpm` package that will make the links and overlaying (installing) it?

But I think it's better to include the fix in the next RPM release.

**Comment by tsilvs** [comment]
This is still an issue on Fedora 39, especially on Fedora Silverblue, because the `ln /usr/share/dupeguru/core/pre/_cache.cpython...` workaround is not possible on a read-only system. `/usr` directory is immutable.

@arsenetar @glubsy what are your thoughts?
