### ISSUE TITLE
Disable bold font on reference items

### ISSUE THREAD

**Issue by glubsy** [arsenetar/dupeguru#314]
Please add a simple option to **disable the bold font**, or even better customize **font and colour** for reference items, as well as delta values. 

Having the same font size on both dupes and references is best to **compare filenames** at a glance and make decision quicker as to which one to delete. 

I love Dupeguru, and its programmer. :two_hearts:

**Comment by hsoft** [comment]
Now that you say it, I agree with your assessment: it's easier to compare items when they all have the same font weight.

There's already many options in the preferences and I worry about over-stuffing them with useless preferences. I'd be more inclined to simply remove the bold weight altogether.

Now, the question to ask ourselves is: is this going to have some adverse effect on some users?

**Comment by glubsy** [comment]
If you're worried about the preferences, how about making an editable xml/config/ini file that more adventurous users would use to tweak this kind of things? 
Same with font size and colours. Some people with bad eyesight would love to be able to tweak those for easier use.

**Comment by hsoft** [comment]
> how about making an editable xml/config/ini file that more adventurous users would use to tweak this kind of things?

I guess it could work, but I suspect that it will be impractical when comes implementation time. Anyway, if a PR comes this way with something along those lines, I wouldn't refuse it.

**Comment by hsoft** [comment]
My current stance on dupeGuru development (that is, what I've just answered above) might not be clear, so I added a new [section in the README](https://github.com/hsoft/dupeguru#slowed-development) to make it clear.

**Comment by vertigo220** [comment]
At the very least, there could be a simple toggle to turn it on and off and, in fact, doing so on the main screen may be preferable. I say this because while I often find myself wishing the font sizes were the same, so it would be easier to tell if two or more filenames or paths are the same, I do like the bolded font for helping to quickly differentiate one reference/duplicate set from the next. And since that's the only possible downside I can think of for making the fonts the same, perhaps instead of dealing with the issues of extra complication that you're worried about with adding more options, you could simply get rid of the bold font, making both lines the same font size, and highlight the reference rows a light gray instead. And maybe in addition to that, to further help see when files have the same name or path, they could be highlighted in the case they do. For example, the following:

```
LINE 1 - Filename1.jpg  Path1  (Reference)
LINE 2 - Filename1.jpg  Path2  (Duplicate)
LINE 3 - Filename2.jpg  Path3  (Reference)
LINE 4 - Filename3.jpg  Path3  (Duplicate)
LINE 5 - Filename4.jpg  Path4  (Reference)
LINE 6 - Filename5.jpg  Path5  (Duplicate)
```

would have lines 1, 3, & 5 highlighted gray, with the filename cells of lines 1 & 2 highlighted another color (or the text could be colored instead, which may be even better) and lines 3 & 4 would have the path cells highlighted (or colored font). And to avoid an issue where multiple consecutive groups have identical filenames and/or paths, which would create a run-on of cells with the same coloring scheme, whether that be highlighting or font color, the color used could cycle. For example, if the above example were instead

```
LINE 1 - Filename1.jpg  Path1  (Reference)
LINE 2 - Filename1.jpg  Path2  (Duplicate)
LINE 3 - Filename2.jpg  Path3  (Reference)
LINE 4 - Filename2.jpg  Path3  (Duplicate)
LINE 5 - Filename4.jpg  Path4  (Reference)
LINE 6 - Filename5.jpg  Path5  (Duplicate)
```

you wouldn't want the filename cells for lines 1-4 all colored the same, as that would cause them to blend together, so lines 1 & 2 would use one color, then 3 & 4 would use another, then the next match would use the first color again.

**Comment by glubsy** [comment]
Disabling the bold font is super easy. Simply comment out [that line](https://github.com/arsenetar/dupeguru/blob/de8a0a21b2a96ca62556e1508fbd2de0cfe83b83/qt/results_model.py#L45) (`font.setBold(isBold)`) and it will work just fine.

**Comment by vertigo220** [comment]
It's not about it being "easy." First of all, most people don't know how to or aren't going to compile it themselves, and even if they did, they'd have to either know how to find that line in the code--which, again, most people won't--or, now that you've pointed it out, they'd have to find it through your comment, then comment out the line and build it. That's going to be <1% of users, and that's probably a generous estimate. Easy would be either making it an option or removing it entirely, which then would require a change as suggested above to replace the functionality that would be lost, without which commenting out that line removes the original problem but introduces a new one. And if the user decides at some point they want the bolded font to help differentiate between the groups, they can't simply go back and forth.

**Comment by glubsy** [comment]
I'm not refuting any of this, just wanted to point out where in the source code to look for a starting point. 
Currently I don't have a lot of time to spend on this unfortunately, otherwise I'd gladly work on making it a proper feature. 

All I wanted to do is point out that it shouldn't be that hard to implement. Just need to learn more about how the program loads preferences, tweak the menu by adding the tickbox, etc. 
Maybe I'll get around to doing it eventually.

Let's start simple with a bold toggle for now. The coloring highlights you described might be a bit more work to implement properly.

**Comment by glubsy** [comment]
I've added the option to enable or disable bold font on reference row. See "Bold font for reference".

![2020-04-27_01-32-37](https://user-images.githubusercontent.com/12895548/80322575-5f772500-8826-11ea-97cf-8496b24c7714.png)

I'm closing this issue for now, but @vertigo220 feel free to open a new issue with your highlighting request, I think it would be a good feature to add in order to improve readability. Maybe make a quick picture as a proof-of-concept too.

**Comment by vertigo220** [comment]
Thanks for adding this. I still think it would be better to put the option on the main interface, so it can be switched back and forth as needed while viewing the results. I'll go create an issue for the coloring now.

**Comment by vertigo220** [comment]
Created a new issue for it, please take a look and let me know what you think.
