### ISSUE TITLE
Window error 120

### ISSUE THREAD

**Issue by ghost** [arsenetar/dupeguru#323]
I am running dupeguru on my computer (running Windows 7 home premium) and keep getting a pop-up saying files can't be deleted, error 120. I have tried running dupeguru as an administrator but still the same message. I contacted Hardcoded and was referred here as he doesn't use Windows. Can anyone offer any suggestions or work around?

Thanks,
KJ

**Comment by Sleepingeye** [comment]
This appears to be a permission issue.  I was deduping a hard drive moved from a computer that stopped working onto another computer.  There were tons of long user-id from the old rig that didn't show up right on the new one.

I encountered these errors as well.  The solutions are:
1) Deleting manually (many were duplicated entire folders).
2) Rightclick parent folder / affected files > Properties > Security, then add or change "Everyone" to have all permissions (or at least modify / delete), and remove all others.

This isn't really an error with dupeGuru, though the error message could be a bit better.

**Comment by Klowner666** [comment]
I had a similar problem, with error 120 persisting after modifying the permission issues of the files. (The error message was all scrambled and cut.)
It turned out it was my anti-virus that was preventing the modification of the files. I whitelisted the program and did not encounter any problem from then on. 

It does confirm that this is a permissions issue rather than a problem with dupeGuru. Thanks for addressing the issue.
