### ISSUE TITLE
Please add donate button.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [arsenetar/dupeguru#326]
I used tool. Is good. Want to say thanks. I read author is not interested in continue program dev. But tool is good I want to say for what is done. 

I read author is not interested in tool. But I guess some future way uncover new interesting things into dev like rewriting on Rust for speed or using machine learning for intelligent or checking video duplicates or making step into legal ediscovery (http://www.edrm.net/resources/standards/processing#Deduplication) or making dedup as service.

**Comment by hsoft** [comment]
The problem is that money is not a motivator for me to work on dupeGuru, so even if there was many donations coming in, I wouldn't be motivated to add more features to this application. In fact, that was precisely what happened [towards the end of fairware](http://www.hardcoded.net/articles/phasing-out-fairware).

If another developer starts contributing to dupeGuru and begins saying that she's motivated by money, then we could reconsider soliciting payment from users, but otherwise, I don't see what we'd gain from this.
