### ISSUE TITLE
Support Forum

### ISSUE THREAD

**Issue by Milliways2** [arsenetar/dupeguru#453]
I was reading the dupeGuru documentation, and want to Link deleted files:, but cannot find the  "Deletion Options".

I am using 4.0.3 on macOS 10.13

I was going to pose a question on the Support forums, but the link doesn't work. https://forum.hardcoded.net/1/

**Comment by effndc** [comment]
Did you attempt to delete files?  When you select a file and then pick the menu option to "Send Marked  to Trash" a dialog box will appear presenting the Deletion Options.

**Comment by gitgetgot** [comment]
yeah, instead of trying the intuitive way via the context menu, 
try this:

<img width="285" alt="screen" src="https://user-images.githubusercontent.com/974980/32983854-c10bce04-cc9b-11e7-94be-a32ef1870be0.png">

its not fast nor convenient, but it works :-)
(when you mark the file first, you wish to delete)
