### ISSUE TITLE
dupeGuru PPA is outdated

### ISSUE THREAD

**Issue by seb-1204** [arsenetar/dupeguru#484]
Hello,
I'm not sure if this is the right place to raise this but are there any plans to provide updated versions to the [Ubuntu PPA](https://launchpad.net/~hsoft/+archive/ubuntu/ppa/+packages) ?

The last build is from 2017-08-25, current Ubuntu release is 17.10 (Artful Aardvark) rleased in October 2017.

I thought the building of the DEB files for the PPA is an automated process. So could this be checked and fixed? Unfortunately I'm lacking the skills to be more helpful.

**Comment by hsoft** [comment]
Yeah, I haven't figured out how to automate the process. I have to update it manually.

**Comment by hsoft** [comment]
Please note that this project is [unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). I'm not going to continue updating that PPA. If someone want to maintain a PPA somewhere, I'll be happy to point to it on the website.

**Comment by Cebtenzzre** [comment]
Someone (at this point probably @arsenetar) should set up a build server to be configured to update the PPA, or at least remember to update the PPA when (if?, lol) new releases are built.  I'm considering (co-)maintaining the Arch AUR package(s), which due to the nature of Arch can be capable of building itself.

**Comment by arsenetar** [comment]
I am planning on setting up the Linux packaging to be built with a build server.  I have not setup a PPA before so I have a bit to figure out.

**Comment by DJCrashdummy** [comment]
just a little question:
is it possible to update the "official PPA" or will it be necessary to change to a new one?

**Comment by hsoft** [comment]
The PPA is currently in my personal launchpad namespace. a new PPA will have to be created and will become the official one.

**Comment by DJCrashdummy** [comment]
hmm, i never created a PPA: is there any possibility to notify the people using the current PPA to switch to the new one?
...maybe as a last resort a "fake-update" with a (somehow recurring) notification?

**Comment by Baltix** [comment]
Hi DupeGuru developers :)
I've created a Ubuntu packaging (PPA) team for Dupeguru, see https://launchpad.net/~dupeguru and "official" PPA archive, see https://launchpad.net/~dupeguru/+archive/ubuntu/ppa
Also I've created packaging recipe for automated builds, see https://code.launchpad.net/~dupeguru/+recipe/dupeguru-packages
But currently automated packaging recipe fails, because there are no debian/changelog file in pkg/debian folder :(
I've tried to work-around this issue by nesting help/changelog file to debian/changelog in recipe, but it seems launchpad doesn't allow to nest-part one file, see 
https://help.launchpad.net/Packaging/SourceBuilds/Recipes#nest-part
and https://answers.launchpad.net/launchpad/+question/418253

So, it would be nice if you add correctly formated changelog file to pkg/debian folder.

Btw, I've noticed that @eugenesan manually created DupeGuru 4.0.4 packages, I've copied them to https://launchpad.net/~dupeguru/+archive/ubuntu/ppa :)

**Comment by arsenetar** [comment]
I have pointed to the PPA in the latest release on github, still need to update the website.

**Comment by arsenetar** [comment]
Site is now updated as well. 
@eugenesan & @Baltix what would it take to build packages for Ubuntu 19.04 & 19.10 (the current non-LTS versions)?

**Comment by eugenesan** [comment]
@arsenetar
I didn't try but I am pretty sure the same package can be used on newer Ubuntu releases.

**Comment by ferroao** [comment]
This works for 19.
```
echo 'deb http://ppa.launchpad.net/dupeguru/ppa/ubuntu bionic main' | sudo tee /etc/apt/sources.list.d/dupeguru-repo.list

sudo apt update
sudo apt install dupeguru

sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-37m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/core/pe/_block.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-37m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-37m-x86_64-linux-gnu.so
```
See https://github.com/arsenetar/dupeguru/issues/519

**Comment by greydmiyu** [comment]
20.04 breaks this method.  Ships with Python3 3.8.2.  Changed the link to "38m", fails to find the cache to import.

**Comment by caguiar** [comment]
Would be nice if it worked on 20.04.

**Comment by soredake** [comment]
Any progress on updating ppa? 🥺

**Comment by Baltix** [comment]
Sorry, currently I haven't free time to finish automating packaging building from source, maybe @eugenesan could build packages for 20.04 manually ? python3-send2trash package is in Ubuntu and Debian, so pkg/debian/control file should have this added to Depends line:
Depends: python3-send2trash

**Comment by zeidoo** [comment]
For newbies like me, as a workaround:
- on a Ubuntu 20.04 system (virtualbox and a VM is better because then you don't pollute your main install with build deps)
- download the source code (git clone or just download the zip)
- run the command from the readme `$ bash -c "python3 -m venv --system-site-packages env && source env/bin/activate && pip install -r requirements.txt && python3 build.py --clean && python3 package.py"`

Google the errors you get:
- I had to add `wheel` at the end of `requirements.txt` file
- apt-get install gettext
- apt-get install debhelper

Once done you get a deb file in the `build` folder. Double click and install. Program starts, not sure if everything is working.

Edit:
An alternative workaround, that I have tried and is working, is to drop the "m" in the link name, such as (note that 36m could be 35m depends on the installed pkg):

`sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so`

`sudo ln /usr/share/dupeguru/core/pe/_block.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so`

`sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so`


PS: I love dupeGuru, if I can help with anything (dev, albeit noob with python, or documentation or anything other), please send me a message and let's coordinate.

**Comment by mad-ady** [comment]
When trying to build on Ubuntu 20.04, I get this error:
```
bash -c "python3 -m venv --system-site-packages env && source env/bin/activate && pip install -r requirements.txt && python3 build.py --clean && python3 package.py"
Requirement already satisfied: Send2Trash>=1.3.0 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: sphinx>=1.2.2 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: polib>=1.0.4 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: hsaudiotag3k>=1.1.3 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (1.1.3.post1)
Requirement already satisfied: requests>=2.5.0 in /usr/lib/python3/dist-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: sphinxcontrib-jsmath in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: sphinxcontrib-devhelp in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (20.3)
Requirement already satisfied: sphinxcontrib-htmlhelp in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: snowballstemmer>=1.1 in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (0.7.12)
Requirement already satisfied: imagesize in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: setuptools in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (44.0.0)
Requirement already satisfied: babel>=1.3 in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (2.8.0)
Requirement already satisfied: Jinja2>=2.3 in /usr/lib/python3/dist-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: docutils>=0.12 in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (0.16)
Requirement already satisfied: Pygments>=2.0 in /usr/lib/python3/dist-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: sphinxcontrib-applehelp in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: sphinxcontrib-serializinghtml in ./env/lib/python3.8/site-packages (from sphinx>=1.2.2->-r requirements.txt (line 2)) (1.1.4)
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3/dist-packages (from babel>=1.3->sphinx>=1.2.2->-r requirements.txt (line 2)) (2019.3)
Traceback (most recent call last):
  File "build.py", line 14, in <module>
    from hscommon import sphinxgen
ImportError: cannot import name 'sphinxgen' from 'hscommon' (unknown location)
```
I'll try the old bionic ppa...

**Comment by soredake** [comment]
So, groovy releases today......

**Comment by soredake** [comment]
https://flathub.org/apps/details/com.neatdecisions.Detwinner
https://github.com/neatdecisions/detwinner
https://github.com/qarmin/czkawka

**Comment by Mannshoch** [comment]
Hirsute is at moment the actual release. 

Any News on this @eugenesan ?

**Comment by eugenesan** [comment]
@Mannshoch 
Looks like there is some confusion with PPAs.

I've uploaded packages to https://launchpad.net/~dupeguru/+archive/ubuntu/ppa a month or so ago.
I think https://launchpad.net/~hsoft/+archive/ubuntu/ppa/+packages repository belong to original author and it is not maintained.

**Comment by glubsy** [comment]
@eugenesan if it's @hsoft you are talking about, he can be also reached on IRC if I recall correctly. Perhaps he would be willing to transfer ownership of the repo to someone more active.

**Comment by eugenesan** [comment]
@glubsy Why would you want the author to transfer his personal repo?

https://launchpad.net/~dupeguru/+archive/ubuntu/ppa is the official repo.
The author created it to allow other to post new releases.
4 people related to the project have access to the repo.
If there are additional volunteers capable of maintaining packages, they are welcome to state their case to one of  current maintainers and apply using https://launchpad.net/~dupeguru/+members

**Comment by glubsy** [comment]
@eugenesan I see, thanks for clarifying.

**Comment by arsenetar** [comment]
Made some additions to the project in a685524dd51138cd2f56b04b86ad08d860e74355, which from my prior work into getting automated PPA builds working seemed to help.  Not complete, and still needs more investigation, I am going after the automated PPA builds as a solution to this issue as that seems to be the most maintainable long term.

**Comment by eugenesan** [comment]
@arsenetar 
Great, standard builds would be really nice.
Once the build system will be somewhat ready, let me know if you need assistance with Debian packaging or/and PPA automated builds (recipes).

**Comment by Baneeishaque** [comment]
Please update PPA for Ubuntu 21.10.

**Comment by Mannshoch** [comment]
I would say, Please update PPA for 22.04 (beta) also, so dupeGuru is ready if 22.04 get released.

**Comment by eugenesan** [comment]
New release of DupeGuru is about to drop any day now.
Once it is released, I am going to upload it to PPA for 20.04 and 22.04.
You can monitor the progress here: https://github.com/arsenetar/dupeguru/issues/928

@Baneeishaque
Per your request, I will attempt to upload to 21.10 but you are on your own.
Non-LTS Ubuntu releases are not widely used and have extremely short support cycle that doesn't justify our efforts as volunteers. I hope you understand.

**Comment by eugenesan** [comment]
Dupeguru PPA has been updated to version 4.2.0.

Supported releases are: Focal (20.04) and Jammy (22.04).

Packages also uploaded for Bionic (18.04) and Impish (21.10)

**Comment by arsenetar** [comment]
Closing this as latest release should have resolved this.
