### ISSUE TITLE
flatpak version

### ISSUE THREAD

**Issue by soredake** [arsenetar/dupeguru#661]
Would be nice to have distro-independent version.

**Comment by darkdragon-001** [comment]
[This](https://github.com/flathub/net.ankiweb.Anki/blob/master/net.ankiweb.Anki.yaml) could be used as a starting point.

**Comment by ramcq** [comment]
Hi folks, I've made up a Flatpak at https://github.com/ramcq/net.voltaicideas.dupeGuru which I am ready to submit to Flathub for build/distribution. Are you happy for me to do this? We can arrange for you to have direct access to the GitHub repo and can walk you through how updates are made if you'd like to be able to release Flatpaks along with the new upstream releases.

**Comment by arsenetar** [comment]
@ramcq Cool, I have thought about looking into this or a snap, but had enough fixing all the other packaging issues that I decided to work on the application code instead for awhile.  I don't have any issues with this.  If there is a way to automate the Flatpak release alongside the releases here that would be cool.

**Comment by ramcq** [comment]
Well, I'm a Flatpak guy rather than a Snap guy so I can't help with that, but Flathub is approaching 1 million active users so I think we're not doing too badly. ;)

I believe there are ways to build your Flatpaks using a GitHub action and then push it to Flathub as a binary - OBS Studio does this - but I've never used a GitHub action so I am a little green at this. The usual Flathub approach is a repo under the flathub org that has the manifest files and the Buildbot builds any updates from there. There is a bot that can monitor new versions and propsoe PRs to the Flathub repo - maybe that's enough. You can have access to that Flathub repo from the start, and then we could maybe try and figure out how we could send a PR when new tags are added here?

Ideally new releases would get a new entry in the appdata file (https://github.com/ramcq/net.voltaicideas.dupeGuru/blob/master/net.voltaicideas.dupeGuru.appdata.xml) so that software centers can show the changes/updates to users when updates are available. Maybe we could include that file upstream, and look at automating the updates to that when there are new releases? That's the most manual part.

**Comment by darkdragon-001** [comment]
How can I add such a bot to a Flathub repository (would be really handy for other projects of mine)?

Apart from that, Github has available actions to create a PR in other repos, so if the change would be reduced to a single version number, this could be accomplished easily.

Totally agree that `appdata.xml` should be generated as part of the normal build. I think libraries could exist for this as it is an open standard also used elsewhere.

**Comment by arsenetar** [comment]
@ramcq Yeah it would be possible to generate that metadata file for appdata from this repository without much work.  I would probably set that up in an action that triggers on releases here and then opens the PR over there if that is really all we need to update.  Once there is a starting point over there I think we can look into the automation.

**Comment by arsenetar** [comment]
Ref #888

**Comment by arsenetar** [comment]
@ramcq  Noticed the flatpak build failed due to no screenshot tags, I uploaded two image to the site at:
- https://dupeguru.voltaicideas.net/assets/screenshots/Directories.png
- https://dupeguru.voltaicideas.net/assets/screenshots/Results.png

They could be used for this (granted they are windows screenshots, but it is really the same layout).

**Comment by soredake** [comment]
https://github.com/flathub/flathub/pull/3040

**Comment by soredake** [comment]
I've lost interest in linux a long time ago.
