### ISSUE TITLE
virustotal.com says infected with HW32.Packed (vendor Bkav)

### ISSUE THREAD

**Issue by al3xander** [arsenetar/dupeguru#670]
If you upload the installer dupeGuru_win64_4.0.4.exe to www.virustotal.com it shows that one of 71 virusscanners is showing the HW32.Packed virus.

The result can also be seen here:
https://www.virustotal.com/gui/file/72637b8d526d97c7b1836857f4012de831a07b3f156028b1b854f1e6e6fd1d84/detection

is there any information about that?

**Comment by glubsy** [comment]
Packed doesn't mean it's a virus. It means the code is compressed in the installer executable file. This is most likely a false positive. Check the details on that page and you'll see there is nothing suspicious at all. 
In doubt, you can compile everything yourself, it's libre and open-source software after all.

**Comment by arsenetar** [comment]
This has been caused in the past due to python being embedded in the app. Additionally, it could be how the installer packs the data. If you downloaded the executable from https://github.com/arsenetar/dupeguru/releases/download/4.0.4/dupeGuru_win64_4.0.4.exe and verified it with https://github.com/arsenetar/dupeguru/releases/download/4.0.4/dupeGuru_win64_4.0.4.exe.sig then I would not expect there to be any issue.
