### ISSUE TITLE
no repeated MD5 hashing.

### ISSUE THREAD

**Issue by D33M0N** [arsenetar/dupeguru#674]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I scan my file collection on external NAS + local storage and it does the full MD5 rescan of files.

**Describe the solution you'd like**
some kind of DB with MD5 hash results (with file location+filename, file length and maybe also last modified date) -- no rehashing of the files already present in DB. Especially large files.

**Comment by glubsy** [comment]
I think the ignore list should also use hashes instead of only file paths. Definitely something to look into.

**Comment by james-cook** [comment]
I'm working with historical fragmented data - and this involves scanning and rescanning large sets of files and folders.
For this kind of use case the re-generation of MD5 (or other) hash becomes very time consuming.
Any speed improvement would be a great help. Also, the faster the runs the more easy it is to keep focused. You can afford to do more runs to get a better view of your data. Not to mention reduced HDD wear and tear...

**BUT my suggestion would be not to use a DB or a cache but instead use xattr.**

This is the approach taken by [`rmlint` ](https://github.com/sahib/rmlint). The great advantage is not having to remember and include the correct cache for each run - instead the information is right there 1:1 for each file in the file-system itself.
Perhaps dupeguru could even use the same format - and (optionally) provide some interoperability - e.g. hashes generated by rmlint are recognised (and so speed up) the next dupeguru run and vice versa etc.
Maybe even the PE information could be held in this way too(?) rather than in the current cache.

**Comment by glubsy** [comment]
Not all platforms support extended attributes but it's also an idea worth looking into.

**Comment by Dobatymo** [comment]
I would like to work on this.

However because I want it to be cross-platform I would implement it with a SQLite database. The database should contain: the file path, the file size, last modification date and one or more hashes.
Instead of just calculating the hash, it would check the db for a file with the same path, size and mod date. If there isn't one, it'd calculate it and store it in the database, if there is just use that.
There should probably also be some settings like "use cache db" and 'invalidate cache after x days'.

Is there any feedback regarding this approach? If something like this would be merged, I will implement it.

**Comment by glubsy** [comment]
Yes, that's the approach I had in mind also. Might need a hash for both the file path and the content of the file. This would be useful for the ignore list.

**Comment by Dobatymo** [comment]
Sorry for the long wait. I started working on something like this here https://github.com/arsenetar/dupeguru/pull/942

**Comment by arsenetar** [comment]
Closing as this has been implemented in #942

**Comment by james-cook** [comment]
Looks good. 

I haven't looked at the code but one thing to watch for is any potential for false hashes. 

Rmlint had a problem ca. 2019 which in certain conditions led to dissimilar files having the same hash! It was to do (as far as I remember) with the hash generating code crashing and leaving a default  value as the hash result.
