### ISSUE TITLE
Loading Result of 'Scan Type: Folders' shows only '---' in every table cell

### ISSUE THREAD

**Issue by YEAS175m3** [arsenetar/dupeguru#676]
**Describe the bug**
I came across this problem when scanning my NAS the whole day for duplicate folders. Seeing how many duplicates I had in the result table I decided to save the result to make my delete-decisions the next day.
When Loading the result it took a while (3,66 MB result file, I assume checking the existence of the paths again) but when it finally showed the `dupeGuru Results`-window, every single cell in every column/line showed `---`.
The amount of existing table lines could be correct and in the status bar it showed the amount of duplicate folders and the total size.
When using `Open Selected with Default Application` on a highlighted entry it opened Windows Explorer with the correct Folders.
So the information is definitely loaded and internally available, but it does not show the file names (folder names in this case), folders, kind, size and so on in the table. Same when calling the `Details` for an entry, also only `---`.

Unfortunately this makes it impossible to delete duplicates, so I am running the scan again now and delete  the duplicates immediately without closing dupeGuru. But for other Users or my own future uses a fix of this bug would be helpful!

* I reduced the amount of entries in the result file drastically, it was loaded faster, but same behavior.
* I created a test folder with one text file, copied the folder and run the scan again, same behavior.
* I tested it with `Scan Type: Contents` and loading the result worked fine and showed the file name and folders.
* I uninstalled and re-installed dupeGuru, same results.

**To Reproduce**
1. Create some **dupeguru_test** folder
1. Create a **Folder_1** folder in this **dupeguru_test** folder
1. Create a text file with some example text inside the **Folder_1** folder
1. Copy & Paste the **Folder_1** folder inside the **dupeguru_test** folder and name it **Folder_1_Copy**
1. Add **dupeguru_test** folder to dupeGuru
1. Configure dupeGuru like this:
![dupeGuru_MainWindow](https://user-images.githubusercontent.com/50301063/85581734-22b88600-b63d-11ea-92d2-3fd156368a6d.png)![DupeGuru_Options](https://user-images.githubusercontent.com/50301063/85581931-4d0a4380-b63d-11ea-9c81-cbfbe5f47d80.png)
1. The result should look like this:
![dupeGuru_ResultsAfterSearchFinishes](https://user-images.githubusercontent.com/50301063/85584836-cacf4e80-b63f-11ea-88a5-504af9a6c382.png)
1. `Save Results...` in the **dupeguru_test** folder for example
1. Close dupeGuru
1. Start dupeGuru
1. `Load Results` from saved file
1. After importing the file the `dupeGuru Results`- and `Details`-windows looks like this:
![dupeGuru_ResultsWhenLoadingResults](https://user-images.githubusercontent.com/50301063/85585993-cce5dd00-b640-11ea-825b-3ea799e9612b.png)![dupeGuru_Details](https://user-images.githubusercontent.com/50301063/85586447-3960dc00-b641-11ea-91d2-4c94e5b3bf71.png)
1. The `debug.log` shows this errors:
	> 2020-06-24 10:49:44,323 - WARNING - Exception on GetDisplayInfo for T:\dupeguru_test\Folder_1: 
	> 2020-06-24 10:49:44,327 - WARNING - Exception on GetDisplayInfo for T:\dupeguru_test\Folder_1_Copy: 

**Expected behavior**
When loading the results of a `Scan Type: Folders`-search the table should show the values (file name, folders, ...) in the result table like the result windows does right after the scan.

**Desktop:**
 - OS: Windows 10 Pro (German) - Version 2004 - Build19041.329 - no Updates pending
 - dupeGuru Version 4.0.4 RC (x64) (re-downloaded/re-installed from github on 06-24-2020

**Additional context**
[debug.log](https://github.com/arsenetar/dupeguru/files/4826429/debug.log)

**Note of Thanks**
I love open source software like this and I want to thank everyone who contributes to such projects!
I hope with my first reported problem I can also contribute something - I hope the bug report was okay so far :wink:

**Comment by glubsy** [comment]
Thanks for the (very good) bug report. I can confirm this happens also on (Arch) Linux. 

For reference, the exception is generated [here](https://github.com/arsenetar/dupeguru/blob/master/core/app.py#L542). The type of exception thrown is a NotImplementedError, so it must be hitting this [virtual function](https://github.com/arsenetar/dupeguru/blob/master/core/fs.py#L181).

The problem comes after reading the xml data, in [_get_export_data()](https://github.com/arsenetar/dupeguru/blob/master/core/app.py#L275). The dupe passed to the function is of type "core.fs.Folder", but it seems that we need to call the function defined in [core.se.fs.Folder](https://github.com/arsenetar/dupeguru/blob/master/core/se/fs.py#L46) instead (which seems to be the expected implementation) so perhaps the *type* of this dupe is wrong (core.fs.Folder)?
The DupeGuru.results.groups is most likely not populated with the appropriate type in this specific case. 
In which case the problem would be located somewhere in [core.results.py](https://github.com/arsenetar/dupeguru/blob/master/core/results.py), possibly where we initialize the [groups](https://github.com/arsenetar/dupeguru/blob/master/core/results.py#L279) data member.

Anyway, not sure why that implementation is not being called here.

**Comment by glubsy** [comment]
I have written a [temporary fix here](https://github.com/glubsy/dupeguru/commit/e89156e55c90ef1fb7a51e225fc9372f5c0a66eb) which works so far, but it's only redirecting the exception handling to the appropriate function which is in core.se.fs.Folder. 
Not yet sure how to call this automatically, need to investigate more. 
If anyone has a better insight, let us know.

**Comment by glubsy** [comment]
Turns out maybe [this simple fix ](https://github.com/glubsy/dupeguru/commit/ed64428c80d35afa07004fd47a4218d686c6c94e)is actually the solution? I'll make a pull request for the time being, but it probably needs some more testing (also might need to update the test suite, I'm not sure).

**Comment by arsenetar** [comment]
@YEAS175m3 Thanks, for the detailed report.
@glubsy  Thanks, for fixing this issue.
Since this has been resolved, I am marking this issue as closed.
