### ISSUE TITLE
Incompatible Qt library (5.15.0)

### ISSUE THREAD

**Issue by Pushkin31** [arsenetar/dupeguru#711]
Maintain the bug [ragouel](https://github.com/arsenetar/dupeguru/issues/710#issue-700357878)
Same problem in many applications

```
Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
[1]    6553 abort (core dumped)  keepassxc
```

```
Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
[1]    7712 abort (core dumped)  flameshot
```
```
(process:8014): Gtk-WARNING **: 23:48:50.885: Locale not supported by C library.
	Using the fallback 'C' locale.
Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
[1]    8014 abort (core dumped)  krita
```

Platform: Arch Linux latest
Qt: 5.15.1
Python: 3.8.5

I only have Qt-base version installed.

**Comment by glubsy** [comment]
You could have posted in the same issue ticket since it is related.

This is most likely an Arch-specific issue which has nothing to do with dupeguru. Please report to the [Arch bug tracker](https://bugs.archlinux.org/) instead.

I suspect you need to update your python-pyqt5 package. [python-pyqt5 5.15.1-1](https://www.archlinux.org/packages/testing/x86_64/python-pyqt5/) has been built today and is in the `testing` Arch repo. Perhaps you need to enable the `testing` repo, or wait for it to be updated in `extra`.

Edit: after [looking around a bit](https://github.com/therecipe/qt/issues/195), it might not be related to pyqt5. 
You could try running the following command and report the output perhaps.

`export QT_DEBUG_PLUGINS=1 ; dupeguru &> dupeguru_qt5_debug.log`

**Comment by Pushkin31** [comment]
The issue was resolved by updating the qt5-styleplugins package
`yay qt5-styleplugins` from aur

**Comment by Pushkin31** [comment]
> Maintain the bug [ragouel](https://github.com/arsenetar/dupeguru/issues/710#issue-700357878)
> Same problem in many applications
> 
> ```
> Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
> [1]    6553 abort (core dumped)  keepassxc
> ```
> 
> ```
> Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
> [1]    7712 abort (core dumped)  flameshot
> ```
> 
> ```
> (process:8014): Gtk-WARNING **: 23:48:50.885: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
> [1]    8014 abort (core dumped)  krita
> ```
> 
> Platform: Arch Linux latest
> Qt: 5.15.1
> Python: 3.8.5
> 
> I only have Qt-base version installed.

**Comment by glubsy** [comment]
Thanks for reporting!
