### ISSUE TITLE
program can't read Japanese characters

### ISSUE THREAD

**Issue by dogeatdogeatdog** [arsenetar/dupeguru#878]
**Describe the bug**
The program has issues reading Japanese characters.

**To Reproduce**
1. Make a folder, choose 2 different songs, copy to folder rename them "02 君のこころは輝いてるかい？ 国木田花丸 Solo Ver" and "02 君のこころは輝いてるかい？ 松浦果南 Solo Ver"
2. Scan the folder with "filename"
3. The song shows as a duplicate even though it's a different song

**Expected behavior**
I expected the program to read the Japanese characters.

**Screenshots**
![Screenshot - 2021-04-28 22_06_00](https://user-images.githubusercontent.com/52548608/116466201-7ce23300-a86e-11eb-8f91-eba71c8132a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.1.1

**Comment by glubsy** [comment]
Thanks for reporting this issue.

Were you using the "Music" Application mode? Are the tags in these files also different? Are there tags at all?

Edit: Was the Scan Type set to "Filename"? Some other scan type?

Ok, I can reproduce. Needs some investigations now. This happens no matter which App mode is selected (Standard or Music).

The problem seems to come from the getwords() function in engine.py. Unicode characters are ignored.
