### ISSUE TITLE
Files which name starts with a period are ignored (e.g.: ".foobar")

### ISSUE THREAD

**Issue by scodro** [arsenetar/dupeguru#985]
If a duplicate file has a name which starts with a period (.) character, apparently it is ignored and not detected

**Steps to reproduce**
1. Open DupeGuru and make sure you UNCHECK option to "Ignore files smaller than..."
2. Unzip [reprod.zip](https://github.com/arsenetar/dupeguru/files/8367434/reprod.zip)
3. Add both directories "a" and "b" to the list of directories to be scanned
4. Start Scan and you will get the "No duplicates found" result dialog, despite files on zip file are identical

**Operating System**
 - OS: Windows 8.1 Single Language
 - Version 6.3.9600
 
**DupeGuru versions**
I confirmed this bug manifests in versions with installer "dupeGuru_win64_4.2.1.exe" and "dupeGuru_win64_4.1.1.exe"
In previous version with installer "dupeGuru_win64_4.0.4.exe" this bug did not manifest — that is — the duplicate file is detected (that's the version I'm sticking with until this issue is gone)

**Comment by arsenetar** [comment]
This is actually not a bug, but is due to the additional feature of exclusion filters that was added in 4.1.0.  If you go to the Exclusion Filters from the View menu, you can customize the options there, several widely used options (defaults) are populated the first time dupeGuru is run. Below is what you would have to disable to get the result you are looking for:
![image](https://user-images.githubusercontent.com/1545435/160519448-f196bde3-8307-403c-9c9f-64bf27363622.png)
Using the defaults gives the results you have, unselecting the `^\..*` regex removes the filtering out of files starting with `.`.

Edit: I did verify this behavior against the provided zip.

**Comment by scodro** [comment]
Just checked here with my actual files and DupeGuru version 4.2.1 and it detected duplicates correctly.
Sorry for having not noticed that feature, and thank you for the promptness in addressing the issue.
